Update main_app-advanced3-3.yml

diff --git a/.github/workflows/main_app-advanced3-3.yml b/.github/workflows/main_app-advanced3-3.yml
--- a/.github/workflows/main_app-advanced3-3.yml
+++ b/.github/workflows/main_app-advanced3-3.yml
@@ -13,10 +13,11 @@ jobs:
   build:
     runs-on: ubuntu-latest
     permissions:
-      contents: read #This is required for actions/checkout
+      contents: read # This is required for actions/checkout
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
       - name: Set up Node.js version
         uses: actions/setup-node@v3
@@ -29,8 +30,33 @@ jobs:
           npm run build --if-present
           npm run test --if-present
 
+      - name: Copy artifact for deployment job
+        run: |
+          mkdir -p deploy
+          if [ -d ".next/standalone" ]; then
+            cp -r .next/standalone/ ./deploy
+          else
+            echo ".next/standalone directory not found"
+          fi
+
+          if [ -d "public" ]; then
+            cp -r public ./deploy
+          else
+            echo "public directory not found, skipping"
+          fi
+
+          if [ -d ".next/static" ]; then
+            mkdir -p ./deploy/.next/static
+            cp -r .next/static/. ./deploy/.next/static
+          else
+            echo ".next/static directory not found"
+          fi
+
+          cp package.json ./deploy/ || echo "package.json not found"
+          cp next.config.mjs ./deploy/ || echo "next.config.mjs not found"
+
       - name: Zip artifact for deployment
-        run: zip release.zip ./* -r
+        run: zip -r release.zip ./deploy
 
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v4
@@ -54,11 +80,11 @@ jobs:
       - name: Unzip artifact for deployment
         run: unzip release.zip
       
-      - name: 'Deploy to Azure Web App'
+      - name: Deploy to Azure Web App
         id: deploy-to-webapp
         uses: azure/webapps-deploy@v3
         with:
           app-name: 'app-advanced3-3'
           slot-name: 'Production'
-          package: .
-          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E33BABA90F134DFFB49EEAD990CDD7E7 }}
+          package: ./deploy
+          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
